/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OriginalindexImport } from './routes/original_index'
import { Route as NavbarImport } from './routes/_navbar'
import { Route as NavbarIndexImport } from './routes/_navbar/index'
import { Route as NavbarModulesIndexImport } from './routes/_navbar/modules/index'
import { Route as NavbarModulesModuleIndexImport } from './routes/_navbar/modules/$module/index'
import { Route as NavbarModulesModuleActivityIndexImport } from './routes/_navbar/modules/$module/activity/index'
import { Route as NavbarModulesModuleActivityIdImport } from './routes/_navbar/modules/$module/activity/$id'

// Create/Update Routes

const OriginalindexRoute = OriginalindexImport.update({
  path: '/original_index',
  getParentRoute: () => rootRoute,
} as any)

const NavbarRoute = NavbarImport.update({
  id: '/_navbar',
  getParentRoute: () => rootRoute,
} as any)

const NavbarIndexRoute = NavbarIndexImport.update({
  path: '/',
  getParentRoute: () => NavbarRoute,
} as any)

const NavbarModulesIndexRoute = NavbarModulesIndexImport.update({
  path: '/modules/',
  getParentRoute: () => NavbarRoute,
} as any)

const NavbarModulesModuleIndexRoute = NavbarModulesModuleIndexImport.update({
  path: '/modules/$module/',
  getParentRoute: () => NavbarRoute,
} as any)

const NavbarModulesModuleActivityIndexRoute =
  NavbarModulesModuleActivityIndexImport.update({
    path: '/modules/$module/activity/',
    getParentRoute: () => NavbarRoute,
  } as any)

const NavbarModulesModuleActivityIdRoute =
  NavbarModulesModuleActivityIdImport.update({
    path: '/modules/$module/activity/$id',
    getParentRoute: () => NavbarRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_navbar': {
      id: '/_navbar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NavbarImport
      parentRoute: typeof rootRoute
    }
    '/original_index': {
      id: '/original_index'
      path: '/original_index'
      fullPath: '/original_index'
      preLoaderRoute: typeof OriginalindexImport
      parentRoute: typeof rootRoute
    }
    '/_navbar/': {
      id: '/_navbar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NavbarIndexImport
      parentRoute: typeof NavbarImport
    }
    '/_navbar/modules/': {
      id: '/_navbar/modules/'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof NavbarModulesIndexImport
      parentRoute: typeof NavbarImport
    }
    '/_navbar/modules/$module/': {
      id: '/_navbar/modules/$module/'
      path: '/modules/$module'
      fullPath: '/modules/$module'
      preLoaderRoute: typeof NavbarModulesModuleIndexImport
      parentRoute: typeof NavbarImport
    }
    '/_navbar/modules/$module/activity/$id': {
      id: '/_navbar/modules/$module/activity/$id'
      path: '/modules/$module/activity/$id'
      fullPath: '/modules/$module/activity/$id'
      preLoaderRoute: typeof NavbarModulesModuleActivityIdImport
      parentRoute: typeof NavbarImport
    }
    '/_navbar/modules/$module/activity/': {
      id: '/_navbar/modules/$module/activity/'
      path: '/modules/$module/activity'
      fullPath: '/modules/$module/activity'
      preLoaderRoute: typeof NavbarModulesModuleActivityIndexImport
      parentRoute: typeof NavbarImport
    }
  }
}

// Create and export the route tree

interface NavbarRouteChildren {
  NavbarIndexRoute: typeof NavbarIndexRoute
  NavbarModulesIndexRoute: typeof NavbarModulesIndexRoute
  NavbarModulesModuleIndexRoute: typeof NavbarModulesModuleIndexRoute
  NavbarModulesModuleActivityIdRoute: typeof NavbarModulesModuleActivityIdRoute
  NavbarModulesModuleActivityIndexRoute: typeof NavbarModulesModuleActivityIndexRoute
}

const NavbarRouteChildren: NavbarRouteChildren = {
  NavbarIndexRoute: NavbarIndexRoute,
  NavbarModulesIndexRoute: NavbarModulesIndexRoute,
  NavbarModulesModuleIndexRoute: NavbarModulesModuleIndexRoute,
  NavbarModulesModuleActivityIdRoute: NavbarModulesModuleActivityIdRoute,
  NavbarModulesModuleActivityIndexRoute: NavbarModulesModuleActivityIndexRoute,
}

const NavbarRouteWithChildren =
  NavbarRoute._addFileChildren(NavbarRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof NavbarRouteWithChildren
  '/original_index': typeof OriginalindexRoute
  '/': typeof NavbarIndexRoute
  '/modules': typeof NavbarModulesIndexRoute
  '/modules/$module': typeof NavbarModulesModuleIndexRoute
  '/modules/$module/activity/$id': typeof NavbarModulesModuleActivityIdRoute
  '/modules/$module/activity': typeof NavbarModulesModuleActivityIndexRoute
}

export interface FileRoutesByTo {
  '/original_index': typeof OriginalindexRoute
  '/': typeof NavbarIndexRoute
  '/modules': typeof NavbarModulesIndexRoute
  '/modules/$module': typeof NavbarModulesModuleIndexRoute
  '/modules/$module/activity/$id': typeof NavbarModulesModuleActivityIdRoute
  '/modules/$module/activity': typeof NavbarModulesModuleActivityIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_navbar': typeof NavbarRouteWithChildren
  '/original_index': typeof OriginalindexRoute
  '/_navbar/': typeof NavbarIndexRoute
  '/_navbar/modules/': typeof NavbarModulesIndexRoute
  '/_navbar/modules/$module/': typeof NavbarModulesModuleIndexRoute
  '/_navbar/modules/$module/activity/$id': typeof NavbarModulesModuleActivityIdRoute
  '/_navbar/modules/$module/activity/': typeof NavbarModulesModuleActivityIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/original_index'
    | '/'
    | '/modules'
    | '/modules/$module'
    | '/modules/$module/activity/$id'
    | '/modules/$module/activity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/original_index'
    | '/'
    | '/modules'
    | '/modules/$module'
    | '/modules/$module/activity/$id'
    | '/modules/$module/activity'
  id:
    | '__root__'
    | '/_navbar'
    | '/original_index'
    | '/_navbar/'
    | '/_navbar/modules/'
    | '/_navbar/modules/$module/'
    | '/_navbar/modules/$module/activity/$id'
    | '/_navbar/modules/$module/activity/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  NavbarRoute: typeof NavbarRouteWithChildren
  OriginalindexRoute: typeof OriginalindexRoute
}

const rootRouteChildren: RootRouteChildren = {
  NavbarRoute: NavbarRouteWithChildren,
  OriginalindexRoute: OriginalindexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_navbar",
        "/original_index"
      ]
    },
    "/_navbar": {
      "filePath": "_navbar.tsx",
      "children": [
        "/_navbar/",
        "/_navbar/modules/",
        "/_navbar/modules/$module/",
        "/_navbar/modules/$module/activity/$id",
        "/_navbar/modules/$module/activity/"
      ]
    },
    "/original_index": {
      "filePath": "original_index.tsx"
    },
    "/_navbar/": {
      "filePath": "_navbar/index.tsx",
      "parent": "/_navbar"
    },
    "/_navbar/modules/": {
      "filePath": "_navbar/modules/index.tsx",
      "parent": "/_navbar"
    },
    "/_navbar/modules/$module/": {
      "filePath": "_navbar/modules/$module/index.tsx",
      "parent": "/_navbar"
    },
    "/_navbar/modules/$module/activity/$id": {
      "filePath": "_navbar/modules/$module/activity/$id.tsx",
      "parent": "/_navbar"
    },
    "/_navbar/modules/$module/activity/": {
      "filePath": "_navbar/modules/$module/activity/index.tsx",
      "parent": "/_navbar"
    }
  }
}
ROUTE_MANIFEST_END */
